apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: "Florence"
  name: "florence"
  description: "The publishing platform used by the ONS website"
  tags:
    - javascript
  annotations:
    github.com/project-slug: backstage-dummy-org/florence
    # backstage.io/techdocs-ref: dir:.
  links:
  - title: ONS Website
    url: https://www.ons.gov.uk/
    icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: "digital-publishing"
  dependsOn: 
    - component:zebedee
  system: ons-website
